### PR TITLE
Created flat-banner and flat-tile elements

### PR DESCRIPTION
**Pull request by ZanyHunter**
Added a banner and grid of elements that uses a flat style to have a title and subtitle with a background image

### CODE REVIEW

**Comment by ZanyHunter** [comment]
I'm assuming we need to change the images in the items. @silentsonata, who do you want to find images?

**Comment by silentsonata** [comment]
Good call. Let me take a look at them. I would love to replace them all with actual photos from the church but that might be an unrealistic goal.

**Comment by ZanyHunter** [comment]
Strange bug with the grid items where they appear condensed on Firefox on Android. Chrome on Android works fine.

**Comment by silentsonata** [comment]
Actually....I'm going to close this pull request because I want to do some more things before we merge this with the master. I would love to implement this in all the pages before merging with the master.

**Pull request closed without merging**
